cache:
  directories:
    - $HOME/.composer/cache

addons:
  homebrew:
    packages:
    - php
    - composer

matrix:
  allow_failures:
    - os: windows
      language: node_js
  include:
    - os: linux
      dist: trusty
      language: php
      php: 7.3
      env:
        - DEPS=latest
    - os: linux
      dist: trusty
      language: php
      php: 7.3
      env:
        - DEPS=lowest
    - os: linux
      dist: trusty
      language: php
      php: 7.3
      env:
        - DEPS=locked
        - CHECK_CS=true
        - TEST_COVERAGE=true
        - CHECK_PHPSTAN=true
    - os: linux
      dist: trusty
      language: php
      php: 7.4
      env:
        - DEPS=latest
    - os: linux
      dist: xenial
      language: php
      php: 8.0
      env:
        - DEPS=latest
    - os: windows
      env:
        - DEPS=locked
        - CHECK_CS=false
        - TEST_COVERAGE=false
        - CHECK_PHPSTAN=false
      language: node_js
      node_js: 10
      before_install:
        - choco install php composer
        - export PATH=/c/tools/php74:/c/ProgramData/ComposerSetup/bin:$PATH
        - PHP_EXTENSIONS="curl bz2 gd2"
        - for php_ext in $PHP_EXTENSIONS ; do sed -i -e "s/^;extension=${php_ext}/extension=${php_ext}/" /c/tools/php74/php.ini ; done
        - sed -i -e 's/^memory_limit = .*/memory_limit = -1/' /c/tools/php74/php.ini
        - find . -type f -name "*.php" -print0 | xargs -0 sed -i ':a;N;$!ba;s/\r//g'
    - os: osx
      language: node_js
      env:
        - DEPS=locked
        - CHECK_CS=false
        - TEST_COVERAGE=false
        - CHECK_PHPSTAN=false
      node_js: 10
      addons:
        homebrew:
          packages:
            - php
            - composer
          update: true

before_install:
  - travis_retry composer self-update
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'locked' ]]; then travis_retry composer install --no-interaction --ignore-platform-reqs ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then stty cols 120; fi
  - COLUMNS=120 composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then composer test ; fi
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi
  - if [[ $CHECK_PHPSTAN == 'true' ]]; then composer phpstan || true ; fi

after_script:
  - if [[ $TEST_COVERAGE = 'true' ]]; then travis_retry wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover clover.xml ; fi

notifications:
  irc: "irc.freenode.org#sculpin"
  email: false
